source 'https://rubygems.org'

ruby '3.1.0'

gem 'faraday'
gem 'ruby2_keywords', '~> 0.0.4'
gem 'mustermann'
gem 'rack'
gem 'base64', '~> 0.1.1'
gem 'rack-protection'
gem 'sinatra'
gem 'faraday_middleware'
gem 'gli'
gem 'hashie'
gem 'websocket-driver'
gem 'slack-ruby-client'
