source 'https://rubygems.org'

ruby '2.7.2'

gem 'faraday'
gem 'ruby2_keywords'
gem 'mustermann'
gem 'rack'
gem 'base64'
gem 'rack-protection'
gem 'sinatra'
gem 'faraday_middleware'
gem 'gli'
gem 'hashie'
gem 'websocket-driver'
gem 'slack-ruby-client'
